MvcctExample/Models/Food.cs
using System.ComponentModel.DataAnnotations;
namespace MvcctExample.Models
{
    public class Food
    {
        public int Id { get; set; }
        [MaxLength(64), Required]
        public string ProductName { get; set; }
        [MaxLength(32), Required]
        public string Package { get; set; }
        public decimal UnitPrice { get; set; }
        public bool IsDiscontinued { get; set; }
        public int SupplierId { get; set; }
        public virtual Supplier Supplier { get; set; } 
    }
}

MvcctExample/Models/Supplier.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace MvcctExample.Models
{
    public class Supplier
    {
        public int Id { get; set; }
        [MaxLength(64), Required]
        public string CompanyName { get; set; }
        [MaxLength(128), Required]
        public string ContactName { get; set; }
        [MaxLength(64)]
        public string ContactTitle { get; set; }
        [MaxLength(64), Required]
        public string City { get; set; }
        [MaxLength(64), Required]
        public string Country { get; set; }
        [MaxLength(32), Required]
        public string Phone { get; set; }
        [MaxLength(32)]
        public string Fax { get; set; }
        public virtual ICollection<Food> Products { get; set; }
    }
}

MvcctExample/ViewModels/FoodListViewModel.cs
using MvcControlsToolkit.Core.Business.Utilities;
using MvcControlsToolkit.Core.Views;
using MvcctExample.DTOs;

namespace MvcctExample.ViewModels
{
    public class FoodListViewModel
    {
        public DataPage<FoodDTO> Products { get; set; }
        public QueryDescription Query { get; set; }
    }
}

MvcctExample/Controllers/FoodController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using MvcControlsToolkit.Controllers;
using MvcControlsToolkit.Core.OData;
using MvcctExample.DTOs;
using MvcctExample.Repositories;
using MvcctExample.ViewModels;
namespace MvcctExample.Controllers
{
    public class FoodController : 
        ServerCrudController<FoodDTO, FoodDTO, int?>
    {
        public IWebQueryProvider queryProvider { get; private set; }
        public FoodController(FoodRepository repository,
            IStringLocalizerFactory factory, 
            IHttpContextAccessor accessor,
            IWebQueryProvider queryProvider) 
            : base(factory, accessor)
        {
            Repository = repository;
            this.queryProvider = queryProvider;
        }
        // GET: Food
        [ResponseCache(Duration = 0, NoStore = true)]
        public async Task<ActionResult> Index()
        {
            var query = queryProvider.Parse<FoodDTO>();

            int pg = (int)query.Page;
            var grouping = query.GetGrouping<FoodDTOGrouping>();

            var model = new FoodListViewModel
            {
                Query = query,
                Products =
                    grouping == null ?
                        await Repository.GetPage(
                            query.GetFilterExpression(),
                            query.GetSorting() ??
                                (q => q.OrderBy(m => m.ProductName)),
                            pg, 5)
                        :
                        await Repository.GetPageExtended(
                            query.GetFilterExpression(),
                            query.GetSorting<FoodDTOGrouping>() ??
                                (q => q.OrderBy(m => m.ProductName)),
                            pg, 5,
                            query.GetGrouping<FoodDTOGrouping>())
            };

            return View(model);
        }
        [HttpGet]
        public async Task<ActionResult> GetSuppliers(string search)
        {
            var res = search == null || search.Length < 3 ?
                new List<AutoCompleteItem>() :
                await (Repository as FoodRepository).GetSuppliers(search, 10);
            return Json(res);
        }

    }
}

MvcctExample/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MvcctExample.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

MvcctExample/Views/Food/Index.cshtml
@model  FoodListViewModel
@using MvcctExample.DTOs
@using MvcctExample.ViewModels
@{
    ViewData["Title"] = "Mvcct Grid Example";
    if (Model.Query.AttachedTo == null)
    {
        Model.Query.AttachEndpoint(Url.Action("Index", "Food"));
    }
}
<h2>@ViewData["Title"]</h2>

<form asp-antiforgery="true">
    <div asp-validation-summary="All" class="text-danger"></div>
    <grid asp-for="Products.Data"
            type="Immediate"
            mvc-controller=
                "typeof(MvcctExample.Controllers.FoodController)"
            all-properties="true"
            row-id="readonly-example"
            operations="user => Functionalities.FullInLine 
                    | Functionalities.GroupDetail"
            query-for="Query"
            sorting-clauses="2"
            enable-query="true"
            query-grouping-type="typeof(FoodDTOGrouping)"
            class="table table-condensed table-bordered" >
        <column asp-for="Products.Data.Element().SupplierId">
            <external-key-remote display-property="Products.Data.Element()
                .SupplierCompanyName"
                items-value-property="Value"
                items-display-property="Display"
                items-url="@(Url.Action("GetSuppliers", "Food",
                new { search = "_zzz_" }))"
                dataset-name="suppliers"
                url-token="_zzz_"              
                max-results="20" />
        </column>
        <row-type asp-for="Products.Data.SubInfo<FoodDTOGrouping>().Model"
                  from-row="0">
            <column 
               asp-for="Products.Data.SubElement<FoodDTOGrouping>().SupplierIdCount" />
            <column 
               asp-for="Products.Data.SubElement<FoodDTOGrouping>().PackageCount" />
        </row-type>
        <toolbar zone-name="@LayoutStandardPlaces.Header">
            <pager class="pagination pagination-sm"
                   max-pages="4"
                   page-size-default="5"
                   total-pages="Products.TotalPages" />
            &nbsp;
            <query type="Filtering" />
            <query type="Sorting" />
            <query type="Grouping" />
            <verify-permission 
                    required-permissions="@(Functionalities.Append)">
                <button type="button" data-operation="add append 0"
                        class="btn btn-sm btn-primary">
                    new product
                </button>
            </verify-permission>
        </toolbar>
    </grid>
    
</form>
    @section Scripts {

        <link href="~/lib/awesomplete/awesomplete.css" rel="stylesheet" />
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
        <script src="~/lib/mvcct-controls/mvcct.controls.min.js"></script>
        <script src="~/lib/mvcct-controls/modules/mvcct.controls.ajax.min.js"></script>
        <script src="~/lib/awesomplete/awesomplete.min.js"></script>
        <script src="~/lib/mvcct-controls/modules/mvcct.controls.autocomplete.min.js"></script>
        <script src="~/lib/mvcct-controls/modules/mvcct.controls.serverGrid.min.js"></script>
        <script src="~/lib/mvcct-odata/dest/global/mvcct.odata.min.js"></script>
        <script src="~/lib/mvcct-controls/modules/mvcct.controls.query.min.js"></script>
    }

MvcctExample/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

MvcctExample/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MvcctExample/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run & Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

MvcctExample/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcctExample</title>
    @{ await Html.RenderPartialAsync("_FallbackCss"); }
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"  />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MvcctExample</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Food" asp-action="Index">Mvcct Grid Example</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - MvcctExample</p>
        </footer>
    </div>
    
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @{ await Html.RenderPartialAsync("_GlobalizationScriptsPartial"); }
    @{ await Html.RenderPartialAsync("_EnhancementFallbackPartial"); }
    @RenderSection("Scripts", required: false)
    <script src="~/startupjs/startup.js"></script>
    
</body>
</html>